export interface NeighborhoodInfo {
  name: string;
  description: string;
  vibe: string;
  transitAccess: string;
  rentRange: string;
  notableFeatures: string[];
}

/**
 * Static neighborhood data for all 77 Chicago community areas.
 * Keyed by community area ID (1–77).
 */
export const NEIGHBORHOOD_DATA: Record<string, NeighborhoodInfo> = {
  "1": {
    name: "Rogers Park",
    description: "Rogers Park is Chicago's most northern lakefront neighborhood, known for its diversity and affordability. The area features a vibrant mix of cultures, independent businesses, and easy beach access along Juneway and Loyola beaches.",
    vibe: "Diverse, laid-back, and affordable",
    transitAccess: "Red Line (Morse, Loyola, Jarvis); multiple CTA bus routes",
    rentRange: "$900–$1,500",
    notableFeatures: ["Loyola University campus", "Lakefront beaches", "Diverse dining scene"],
  },
  "2": {
    name: "West Ridge",
    description: "West Ridge, also known as West Rogers Park, is a culturally rich neighborhood home to one of Chicago's largest South Asian communities along Devon Avenue. The area offers affordable housing and a strong sense of community.",
    vibe: "Multicultural, residential, family-friendly",
    transitAccess: "CTA buses along Devon Ave and Western Ave; Brown Line accessible via transfer",
    rentRange: "$850–$1,400",
    notableFeatures: ["Devon Avenue shopping corridor", "Indian & Pakistani restaurants", "Warren Park"],
  },
  "3": {
    name: "Uptown",
    description: "Uptown is a lively neighborhood with a rich musical heritage and diverse population. The area is undergoing significant development while retaining its eclectic character, entertainment venues, and proximity to the lakefront.",
    vibe: "Eclectic, artsy, rapidly developing",
    transitAccess: "Red Line (Wilson, Lawrence); multiple CTA bus routes",
    rentRange: "$1,000–$1,800",
    notableFeatures: ["Aragon Ballroom", "Green Mill jazz club", "Montrose Beach"],
  },
  "4": {
    name: "Lincoln Square",
    description: "Lincoln Square is a charming neighborhood with European roots and a walkable main street. The area is known for its independent shops, family-friendly atmosphere, and the iconic Old Town School of Folk Music.",
    vibe: "Charming, walkable, family-oriented",
    transitAccess: "Brown Line (Western, Rockwell); CTA bus routes along Lincoln Ave",
    rentRange: "$1,100–$1,900",
    notableFeatures: ["Old Town School of Folk Music", "Lincoln Square shopping district", "Welles Park"],
  },
  "5": {
    name: "North Center",
    description: "North Center is a family-friendly neighborhood with tree-lined streets and excellent schools. The area offers a mix of single-family homes and condos, with easy access to the Brown Line and vibrant commercial strips.",
    vibe: "Family-friendly, quiet, residential",
    transitAccess: "Brown Line (Irving Park, Addison); CTA buses along Lincoln and Western",
    rentRange: "$1,200–$2,100",
    notableFeatures: ["St. Ben's neighborhood", "Horner Park", "Craft breweries along Ravenswood"],
  },
  "6": {
    name: "Lake View",
    description: "Lake View is one of Chicago's most popular neighborhoods, encompassing Wrigleyville and Boystown. The area offers excellent dining, nightlife, lakefront access, and the iconic Wrigley Field.",
    vibe: "Lively, young, entertainment-focused",
    transitAccess: "Red/Brown/Purple Lines (Belmont, Addison); extensive bus network",
    rentRange: "$1,200–$2,200",
    notableFeatures: ["Wrigley Field", "Boystown nightlife", "Lakefront Trail access"],
  },
  "7": {
    name: "Lincoln Park",
    description: "Lincoln Park is one of Chicago's most affluent and desirable neighborhoods, featuring the city's largest park, a free zoo, and upscale dining and shopping along Armitage and Halsted.",
    vibe: "Upscale, green, vibrant",
    transitAccess: "Red/Brown/Purple Lines (Fullerton, Armitage); multiple bus routes",
    rentRange: "$1,500–$2,800",
    notableFeatures: ["Lincoln Park Zoo", "DePaul University", "North Avenue Beach"],
  },
  "8": {
    name: "Near North Side",
    description: "The Near North Side includes the Magnificent Mile, Gold Coast, and River North. This is Chicago's premier commercial and luxury residential district with world-class shopping, dining, and cultural attractions.",
    vibe: "Upscale, urban, cosmopolitan",
    transitAccess: "Red Line (Chicago, Grand, Clark/Division); extensive transit options",
    rentRange: "$1,800–$3,500+",
    notableFeatures: ["Magnificent Mile", "Gold Coast historic mansions", "River North galleries"],
  },
  "9": {
    name: "Edison Park",
    description: "Edison Park is Chicago's most northwest neighborhood, with a suburban feel and strong community ties. The area features well-maintained homes, local businesses, and a Metra station for easy commuting.",
    vibe: "Suburban, tight-knit, quiet",
    transitAccess: "Metra UP-NW Line (Edison Park); CTA buses",
    rentRange: "$1,000–$1,600",
    notableFeatures: ["Metra commuter access", "Small-town Main Street feel", "Low crime rates"],
  },
  "10": {
    name: "Norwood Park",
    description: "Norwood Park is a quiet, residential neighborhood on Chicago's far northwest side. The area is known for its bungalows, parks, and family-friendly atmosphere with easy access to O'Hare.",
    vibe: "Quiet, residential, suburban",
    transitAccess: "Blue Line (Harlem); Metra UP-NW Line; CTA buses",
    rentRange: "$950–$1,500",
    notableFeatures: ["Proximity to O'Hare", "Historic bungalows", "Norwood Park nature preserve"],
  },
  "11": {
    name: "Jefferson Park",
    description: "Jefferson Park is a diverse, working-class neighborhood with strong Polish heritage. The area serves as a major CTA transit hub and offers affordable housing with good access to the rest of the city.",
    vibe: "Working-class, diverse, transit-connected",
    transitAccess: "Blue Line (Jefferson Park); Metra UP-NW; major bus hub",
    rentRange: "$900–$1,400",
    notableFeatures: ["Jefferson Park Transit Center", "Polish community heritage", "Jefferson Park"],
  },
  "12": {
    name: "Forest Glen",
    description: "Forest Glen is one of Chicago's most secluded and residential neighborhoods, with large lots, mature trees, and a distinctly suburban character. The area is home to the Bohemian National Cemetery.",
    vibe: "Secluded, residential, green",
    transitAccess: "Metra UP-NW Line (Mayfair); CTA buses along Cicero and Pulaski",
    rentRange: "$1,000–$1,600",
    notableFeatures: ["Bohemian National Cemetery", "Large residential lots", "Forest preserve access"],
  },
  "13": {
    name: "North Park",
    description: "North Park is a quiet residential neighborhood with a mix of brick bungalows and two-flats along the North Branch of the Chicago River. The area is home to North Park University and several nature areas.",
    vibe: "Quiet, residential, nature-adjacent",
    transitAccess: "CTA buses along Pulaski and Foster; Brown Line accessible via transfer",
    rentRange: "$900–$1,400",
    notableFeatures: ["North Park University", "North Branch Trail", "Peterson Garden Project"],
  },
  "14": {
    name: "Albany Park",
    description: "Albany Park is one of Chicago's most ethnically diverse neighborhoods, with thriving Middle Eastern, Korean, and Latin American communities. Lawrence Avenue is a destination for global cuisine.",
    vibe: "Diverse, bustling, food-centric",
    transitAccess: "Brown Line (Kimball, Kedzie); CTA buses along Lawrence and Kedzie",
    rentRange: "$900–$1,400",
    notableFeatures: ["Global cuisine on Lawrence Ave", "North Branch river trail", "Cultural diversity"],
  },
  "15": {
    name: "Portage Park",
    description: "Portage Park is a northwest side neighborhood with a strong working-class character and growing Polish-American community. The area features the historic Portage Theater and the sprawling Portage Park.",
    vibe: "Working-class, family-friendly, community-oriented",
    transitAccess: "Blue Line (Irving Park, Montrose); CTA buses along Irving Park and Central",
    rentRange: "$900–$1,400",
    notableFeatures: ["Portage Park", "Portage Theater", "Six Corners shopping district"],
  },
  "16": {
    name: "Irving Park",
    description: "Irving Park is a residential neighborhood with a mix of historic mansions and two-flats. The area has a diverse population and good transit connections along the Blue and Brown Lines.",
    vibe: "Residential, diverse, historic",
    transitAccess: "Blue Line (Irving Park); Brown Line (Irving Park); CTA buses",
    rentRange: "$900–$1,500",
    notableFeatures: ["Historic Villa district", "Independence Park", "Easy transit access"],
  },
  "17": {
    name: "Dunning",
    description: "Dunning is a quiet residential neighborhood on the far northwest side of Chicago. The area offers affordable housing, parks, and a slower pace of life with proximity to O'Hare airport.",
    vibe: "Quiet, affordable, suburban",
    transitAccess: "Blue Line (Harlem, Montrose); CTA buses",
    rentRange: "$850–$1,300",
    notableFeatures: ["Wright College campus", "Merrimac Park", "O'Hare proximity"],
  },
  "18": {
    name: "Montclare",
    description: "Montclare is a small, predominantly residential community on Chicago's northwest side. The neighborhood is known for its well-kept homes, family atmosphere, and easy access to the Eisenhower Expressway.",
    vibe: "Residential, family-oriented, quiet",
    transitAccess: "CTA buses along Grand and Harlem; Blue Line accessible nearby",
    rentRange: "$850–$1,300",
    notableFeatures: ["Rutherford Sayre Park", "Small-town feel", "Expressway access"],
  },
  "19": {
    name: "Belmont Cragin",
    description: "Belmont Cragin is a densely populated, predominantly Hispanic neighborhood on Chicago's northwest side. The area features busy commercial corridors along Fullerton and Diversey with affordable housing options.",
    vibe: "Bustling, Hispanic heritage, community-driven",
    transitAccess: "CTA buses along Fullerton, Diversey, and Laramie",
    rentRange: "$800–$1,300",
    notableFeatures: ["Riis Park", "Diverse local businesses", "Affordable rents"],
  },
  "20": {
    name: "Hermosa",
    description: "Hermosa is a small, predominantly Latino neighborhood on the northwest side. The area is primarily residential with single-family homes and small apartment buildings, offering affordable rents close to the Blue Line.",
    vibe: "Residential, quiet, affordable",
    transitAccess: "CTA buses along Pulaski and Armitage; Blue Line nearby",
    rentRange: "$800–$1,200",
    notableFeatures: ["Kelvyn Park", "Close to Logan Square", "Affordable housing"],
  },
  "21": {
    name: "Avondale",
    description: "Avondale is a rapidly gentrifying neighborhood with a mix of Polish heritage and new creative businesses. The area features craft breweries, hip restaurants, and affordable housing relative to nearby Logan Square.",
    vibe: "Up-and-coming, creative, diverse",
    transitAccess: "Blue Line (Belmont, Addison); CTA buses along Belmont and Diversey",
    rentRange: "$1,000–$1,600",
    notableFeatures: ["Craft brewery scene", "Diverse dining", "Proximity to Logan Square"],
  },
  "22": {
    name: "Logan Square",
    description: "Logan Square is a trendy neighborhood known for its tree-lined boulevards, historic greystone buildings, and thriving food and arts scene. The area has seen significant development while maintaining its cultural character.",
    vibe: "Trendy, artsy, rapidly developing",
    transitAccess: "Blue Line (Logan Square, California); CTA buses along Milwaukee and Fullerton",
    rentRange: "$1,100–$2,000",
    notableFeatures: ["Logan Square monument", "Milwaukee Ave dining", "Historic boulevards"],
  },
  "23": {
    name: "Humboldt Park",
    description: "Humboldt Park is a vibrant neighborhood centered around its namesake 207-acre park. The area has deep Puerto Rican cultural roots, marked by the iconic steel Puerto Rican flags on Division Street.",
    vibe: "Cultural, vibrant, community-proud",
    transitAccess: "CTA buses along Division, Chicago, and North; Blue Line nearby",
    rentRange: "$850–$1,400",
    notableFeatures: ["Humboldt Park lagoon", "Puerto Rican heritage", "Paseo Boricua on Division St"],
  },
  "24": {
    name: "West Town",
    description: "West Town encompasses the trendy neighborhoods of Wicker Park and Bucktown, known for their boutique shopping, vibrant nightlife, and creative energy. The area is one of Chicago's most walkable and desirable.",
    vibe: "Trendy, walkable, vibrant nightlife",
    transitAccess: "Blue Line (Damen, Division); CTA buses along Milwaukee, Division, and North",
    rentRange: "$1,300–$2,400",
    notableFeatures: ["Wicker Park & Bucktown", "Milwaukee Ave corridor", "Independent boutiques"],
  },
  "25": {
    name: "Austin",
    description: "Austin is Chicago's largest community area by population, located on the far west side. The neighborhood features beautiful Victorian-era architecture and is undergoing community-led revitalization efforts.",
    vibe: "Community-focused, historic architecture, revitalizing",
    transitAccess: "Green Line (Austin, Central); Blue Line (Austin); CTA buses",
    rentRange: "$700–$1,100",
    notableFeatures: ["Victorian architecture", "Columbus Park", "Austin Town Hall"],
  },
  "26": {
    name: "West Garfield Park",
    description: "West Garfield Park is a west side neighborhood anchored by the historic Garfield Park Conservatory. The community is working toward revitalization while preserving its architectural heritage.",
    vibe: "Historic, community-focused, developing",
    transitAccess: "Green Line (Pulaski, Conservatory); CTA buses along Madison and Pulaski",
    rentRange: "$650–$1,000",
    notableFeatures: ["Garfield Park Conservatory", "Historic graystones", "Community gardens"],
  },
  "27": {
    name: "East Garfield Park",
    description: "East Garfield Park is a west side neighborhood adjacent to the Garfield Park Conservatory. The area features affordable housing and growing community investment, with improving transit connections.",
    vibe: "Affordable, community-invested, developing",
    transitAccess: "Green Line (Conservatory, California); CTA buses along Madison",
    rentRange: "$650–$1,000",
    notableFeatures: ["Garfield Park Conservatory access", "Affordable housing", "Community organizations"],
  },
  "28": {
    name: "Near West Side",
    description: "The Near West Side includes the bustling neighborhoods of Greektown, Little Italy, and the Illinois Medical District. The area is home to UIC and features a dynamic mix of dining, culture, and medical institutions.",
    vibe: "Urban, diverse, institutional",
    transitAccess: "Blue/Pink Lines (UIC-Halsted, Racine); multiple CTA buses",
    rentRange: "$1,200–$2,200",
    notableFeatures: ["University of Illinois Chicago", "Greektown restaurants", "Illinois Medical District"],
  },
  "29": {
    name: "North Lawndale",
    description: "North Lawndale is a historically significant west side neighborhood with deep civil rights connections. The area features beautiful but often neglected greystone architecture and is the site of major community development efforts.",
    vibe: "Historic, resilient, community-driven",
    transitAccess: "Pink Line (Kostner, Pulaski); CTA buses along Ogden and Cermak",
    rentRange: "$650–$1,000",
    notableFeatures: ["Historic graystones", "Civil rights heritage", "Douglas Park"],
  },
  "30": {
    name: "South Lawndale",
    description: "South Lawndale, widely known as Little Village, is a vibrant predominantly Mexican-American neighborhood. 26th Street is one of the busiest shopping corridors in Chicago, second only to the Magnificent Mile.",
    vibe: "Vibrant, culturally rich, bustling commerce",
    transitAccess: "Pink Line (Kostner, California); CTA buses along 26th St and Cermak",
    rentRange: "$750–$1,200",
    notableFeatures: ["26th Street shopping", "Little Village Arch", "Mexican-American culture"],
  },
  "31": {
    name: "Lower West Side",
    description: "The Lower West Side, home to the historically Mexican-American neighborhood of Pilsen, is a vibrant arts and cultural hub. The area features colorful murals, galleries, and acclaimed Mexican restaurants.",
    vibe: "Artsy, culturally vibrant, rapidly changing",
    transitAccess: "Pink Line (18th, Damen); CTA buses along 18th St and Halsted",
    rentRange: "$1,000–$1,700",
    notableFeatures: ["Pilsen murals", "National Museum of Mexican Art", "18th Street dining"],
  },
  "32": {
    name: "Loop",
    description: "The Loop is Chicago's central business district and cultural core. Home to iconic architecture, world-class museums, Millennium Park, and the Theater District, it's the heart of the city.",
    vibe: "Urban core, bustling, iconic",
    transitAccess: "All CTA 'L' lines; Metra hub; extensive bus network",
    rentRange: "$1,600–$3,000+",
    notableFeatures: ["Millennium Park", "Art Institute of Chicago", "Chicago Theater District"],
  },
  "33": {
    name: "Near South Side",
    description: "The Near South Side, including the South Loop and Printer's Row, has transformed from an industrial area into a booming residential neighborhood. The area offers easy downtown access, museums, and lakefront parks.",
    vibe: "Modern, urban, rapidly developed",
    transitAccess: "Red/Green/Orange Lines (Roosevelt, Cermak-Chinatown); Metra",
    rentRange: "$1,400–$2,600",
    notableFeatures: ["Museum Campus", "Soldier Field", "Grant Park"],
  },
  "34": {
    name: "Armour Square",
    description: "Armour Square is a compact neighborhood that includes Chinatown and the area around Guaranteed Rate Field. The area offers authentic Chinese dining, cultural institutions, and affordable housing options.",
    vibe: "Cultural, food-centric, compact",
    transitAccess: "Red Line (Sox-35th, Cermak-Chinatown); CTA buses along Wentworth",
    rentRange: "$900–$1,500",
    notableFeatures: ["Chinatown", "Guaranteed Rate Field", "Ping Tom Memorial Park"],
  },
  "35": {
    name: "Douglas",
    description: "Douglas, also known as Bronzeville, is a historically significant African American neighborhood experiencing a renaissance. The area features beautiful Victorian-era buildings and important cultural landmarks.",
    vibe: "Historic, cultural, revitalizing",
    transitAccess: "Green Line (35th-Bronzeville-IIT, Indiana); CTA buses along King Drive",
    rentRange: "$900–$1,500",
    notableFeatures: ["Bronzeville heritage", "IIT campus", "Historic Victory Monument"],
  },
  "36": {
    name: "Oakland",
    description: "Oakland is one of Chicago's smallest community areas, located between Bronzeville and the lakefront. The area is primarily residential with ongoing development and proximity to the lakefront.",
    vibe: "Small, developing, lakefront-adjacent",
    transitAccess: "Green Line (35th-Bronzeville-IIT); CTA buses along Cottage Grove",
    rentRange: "$800–$1,300",
    notableFeatures: ["Lakefront proximity", "Small-town feel in the city", "Developing area"],
  },
  "37": {
    name: "Fuller Park",
    description: "Fuller Park is a small south side community named after its central park. The neighborhood is primarily residential with a tight-knit community and access to public transit along the Dan Ryan corridor.",
    vibe: "Residential, tight-knit, developing",
    transitAccess: "Red Line (47th); CTA buses along Halsted and 47th",
    rentRange: "$650–$950",
    notableFeatures: ["Fuller Park", "Proximity to White Sox stadium", "Affordable housing"],
  },
  "38": {
    name: "Grand Boulevard",
    description: "Grand Boulevard is a historic Bronzeville neighborhood with stunning boulevard homes and deep jazz and blues heritage. The area is home to important institutions like the DuSable Museum.",
    vibe: "Historic, cultural, architecturally rich",
    transitAccess: "Green Line (51st, Garfield); CTA buses along King Drive and Cottage Grove",
    rentRange: "$800–$1,300",
    notableFeatures: ["DuSable Museum", "Historic boulevard homes", "Jazz heritage"],
  },
  "39": {
    name: "Kenwood",
    description: "Kenwood is an affluent south side neighborhood known for its grand mansions and historic architecture. The area gained national attention as the home of the Obama family before their move to the White House.",
    vibe: "Affluent, historic, residential",
    transitAccess: "Metra Electric (Kenwood); CTA buses along 47th and Hyde Park Blvd",
    rentRange: "$1,100–$2,000",
    notableFeatures: ["Historic mansions", "Obama family home", "Lake Michigan proximity"],
  },
  "40": {
    name: "Washington Park",
    description: "Washington Park is centered around its namesake 372-acre park designed by Frederick Law Olmsted. The neighborhood is a historically African American community with significant green space and cultural events.",
    vibe: "Green, community-oriented, historic",
    transitAccess: "Green Line (Garfield, King Drive); CTA buses along Cottage Grove and King Drive",
    rentRange: "$700–$1,100",
    notableFeatures: ["Washington Park (372 acres)", "DuSable Museum nearby", "Bud Billiken Parade route"],
  },
  "41": {
    name: "Hyde Park",
    description: "Hyde Park is an intellectual and cultural hub anchored by the University of Chicago. The neighborhood features the Museum of Science and Industry, diverse dining, independent bookstores, and lakefront access.",
    vibe: "Academic, intellectual, culturally rich",
    transitAccess: "Metra Electric (55th-56th-57th St, 59th St); CTA buses along 55th and Lake Park",
    rentRange: "$1,000–$1,800",
    notableFeatures: ["University of Chicago", "Museum of Science and Industry", "Promontory Point"],
  },
  "42": {
    name: "Woodlawn",
    description: "Woodlawn is a south side neighborhood undergoing significant revitalization, partly driven by the Obama Presidential Center development. The area features historic architecture and growing community investment.",
    vibe: "Revitalizing, community-invested, historic",
    transitAccess: "Green Line (63rd); Metra Electric; CTA buses along 63rd and Cottage Grove",
    rentRange: "$800–$1,300",
    notableFeatures: ["Obama Presidential Center (under construction)", "Jackson Park", "Historic buildings"],
  },
  "43": {
    name: "South Shore",
    description: "South Shore is a lakefront neighborhood on Chicago's south side with beautiful beaches and the historic South Shore Cultural Center. The area offers affordable housing with scenic lake views.",
    vibe: "Lakefront, cultural, affordable",
    transitAccess: "Metra Electric (South Shore, Bryn Mawr, Windsor Park); CTA buses along 71st and Jeffrey",
    rentRange: "$750–$1,200",
    notableFeatures: ["South Shore Cultural Center", "Rainbow Beach", "Jackson Park"],
  },
  "44": {
    name: "Chatham",
    description: "Chatham is a historically middle-class African American neighborhood on the south side. The area is known for its well-maintained brick bungalows, active commercial corridors, and strong community identity.",
    vibe: "Middle-class, community-proud, residential",
    transitAccess: "CTA buses along 79th, Cottage Grove, and King Drive; Red Line nearby",
    rentRange: "$800–$1,200",
    notableFeatures: ["Chatham business district", "Well-maintained bungalows", "Strong community organizations"],
  },
  "45": {
    name: "Avalon Park",
    description: "Avalon Park is a quiet residential neighborhood on Chicago's south side, known for its single-family homes and neighborhood parks. The area offers affordable housing with a strong sense of community.",
    vibe: "Quiet, residential, family-oriented",
    transitAccess: "Metra Electric (83rd St); CTA buses along 79th and Stony Island",
    rentRange: "$750–$1,100",
    notableFeatures: ["Avalon Park", "Single-family homes", "Quiet residential streets"],
  },
  "46": {
    name: "South Chicago",
    description: "South Chicago is a historically working-class neighborhood shaped by the steel industry. The area sits at the mouth of the Calumet River with lakefront access and a diverse, resilient community.",
    vibe: "Working-class, industrial heritage, resilient",
    transitAccess: "Metra Electric (South Chicago branch); CTA buses along Commercial and 87th",
    rentRange: "$700–$1,000",
    notableFeatures: ["Calumet River access", "Steel industry heritage", "Rainbow Beach nearby"],
  },
  "47": {
    name: "Burnside",
    description: "Burnside is one of Chicago's smallest community areas, located on the far south side. The primarily residential neighborhood offers very affordable housing and a quiet, close-knit atmosphere.",
    vibe: "Small, quiet, affordable",
    transitAccess: "CTA buses along 87th and 91st; Metra Rock Island nearby",
    rentRange: "$650–$950",
    notableFeatures: ["Small community feel", "Very affordable", "Proximity to major transit routes"],
  },
  "48": {
    name: "Calumet Heights",
    description: "Calumet Heights is a middle-class residential neighborhood on Chicago's south side. The area features well-maintained homes, parks, and a strong neighborhood identity with good access to the Skyway.",
    vibe: "Middle-class, residential, well-maintained",
    transitAccess: "CTA buses along 87th and Stony Island; Metra Electric nearby",
    rentRange: "$800–$1,200",
    notableFeatures: ["Well-kept residential blocks", "Calumet Park", "Easy Skyway access"],
  },
  "49": {
    name: "Roseland",
    description: "Roseland is a large south side neighborhood with a rich history as a company town. The area features diverse architecture, active churches, and a community working toward economic revitalization.",
    vibe: "Historic, community-driven, faith-based",
    transitAccess: "Metra Rock Island (111th St); CTA buses along Michigan Ave and 111th",
    rentRange: "$650–$1,000",
    notableFeatures: ["Historic architecture", "Strong church community", "Pullman National Monument nearby"],
  },
  "50": {
    name: "Pullman",
    description: "Pullman is a nationally significant historic neighborhood, built as a planned company town in the 1880s. The area is a National Monument featuring distinctive row houses and the historic Hotel Florence.",
    vibe: "Historic, architecturally significant, preserved",
    transitAccess: "Metra Electric (Pullman, 111th St); CTA buses along Cottage Grove and 111th",
    rentRange: "$750–$1,100",
    notableFeatures: ["Pullman National Monument", "Historic row houses", "Hotel Florence"],
  },
  "51": {
    name: "South Deering",
    description: "South Deering is a far south side neighborhood with industrial roots along the Calumet River. The area offers affordable housing and is seeing environmental remediation efforts along its waterways.",
    vibe: "Industrial heritage, affordable, developing",
    transitAccess: "CTA buses along Torrence and 106th; Metra Electric nearby",
    rentRange: "$650–$950",
    notableFeatures: ["Calumet River industrial corridor", "Big Marsh Park", "Affordable housing"],
  },
  "52": {
    name: "East Side",
    description: "East Side is Chicago's most southeastern neighborhood, bordered by the state line and the Calumet River. The area has a strong working-class identity with a significant Mexican-American population.",
    vibe: "Working-class, tight-knit, border community",
    transitAccess: "CTA buses along 106th and Ewing; close to Indiana transit",
    rentRange: "$700–$1,000",
    notableFeatures: ["Calumet River access", "State line location", "Working-class heritage"],
  },
  "53": {
    name: "West Pullman",
    description: "West Pullman is a far south side residential neighborhood with a mix of single-family homes and commercial corridors. The area offers very affordable housing and access to forest preserves.",
    vibe: "Residential, affordable, green spaces",
    transitAccess: "Metra Rock Island (119th St); CTA buses along 119th and Halsted",
    rentRange: "$650–$950",
    notableFeatures: ["Affordable single-family homes", "Forest preserve access", "Quiet streets"],
  },
  "54": {
    name: "Riverdale",
    description: "Riverdale is Chicago's southernmost community area, featuring the Altgeld Gardens housing development and proximity to the Calumet River and forest preserves.",
    vibe: "Far south, residential, nature-adjacent",
    transitAccess: "CTA buses along 130th; Metra Electric (Riverdale)",
    rentRange: "$600–$900",
    notableFeatures: ["Beaubien Forest Preserve", "Altgeld Gardens", "Calumet River access"],
  },
  "55": {
    name: "Hegewisch",
    description: "Hegewisch is Chicago's most isolated neighborhood, surrounded by the state line, marshlands, and industrial areas. The area has a small-town feel with a strong Eastern European heritage.",
    vibe: "Isolated, small-town feel, heritage-rich",
    transitAccess: "Metra Electric (Hegewisch); CTA buses along 130th and Torrence",
    rentRange: "$700–$1,000",
    notableFeatures: ["Small-town atmosphere", "Wolf Lake", "Eastern European heritage"],
  },
  "56": {
    name: "Garfield Ridge",
    description: "Garfield Ridge is a southwest side neighborhood near Midway Airport. The area is primarily residential with a mix of bungalows and brick homes, offering affordable housing with easy airport access.",
    vibe: "Residential, affordable, airport-adjacent",
    transitAccess: "Orange Line (Midway, Pulaski); CTA buses along Archer and 55th",
    rentRange: "$850–$1,300",
    notableFeatures: ["Midway Airport proximity", "Bungalow architecture", "Le Claire Courts redevelopment"],
  },
  "57": {
    name: "Archer Heights",
    description: "Archer Heights is a quiet southwest side neighborhood with a strong Polish-American heritage. The area features well-maintained homes along Archer Avenue and affordable rents.",
    vibe: "Quiet, Polish heritage, affordable",
    transitAccess: "Orange Line (Pulaski); CTA buses along Archer Ave",
    rentRange: "$800–$1,200",
    notableFeatures: ["Polish-American heritage", "Archer Avenue corridor", "Affordable bungalows"],
  },
  "58": {
    name: "Brighton Park",
    description: "Brighton Park is a predominantly Hispanic southwest side neighborhood with a strong sense of community. The area features affordable housing, family-owned businesses, and the popular Brighton Park.",
    vibe: "Family-oriented, Hispanic heritage, affordable",
    transitAccess: "CTA buses along Archer, Western, and 47th; Orange Line nearby",
    rentRange: "$800–$1,200",
    notableFeatures: ["Brighton Park", "Affordable family housing", "Diverse small businesses"],
  },
  "59": {
    name: "McKinley Park",
    description: "McKinley Park is a small, diverse neighborhood centered around its namesake park and pool. The area is increasingly popular for its affordability, central location, and proximity to Pilsen and Bridgeport.",
    vibe: "Diverse, up-and-coming, centrally located",
    transitAccess: "Orange Line (35th/Archer); CTA buses along Archer and Western",
    rentRange: "$900–$1,400",
    notableFeatures: ["McKinley Park & pool", "Central location", "Growing dining scene"],
  },
  "60": {
    name: "Bridgeport",
    description: "Bridgeport is a historically Irish-American neighborhood that's become increasingly diverse and hip. The area is home to Guaranteed Rate Field, an emerging arts scene, and excellent Chinese food.",
    vibe: "Diverse, artsy, neighborhood-proud",
    transitAccess: "Red Line (Sox-35th); Orange Line (Halsted); CTA buses along Halsted and 35th",
    rentRange: "$900–$1,500",
    notableFeatures: ["Guaranteed Rate Field", "Palmisano Park", "Zhou B Art Center"],
  },
  "61": {
    name: "New City",
    description: "New City, historically known as Back of the Yards, is a working-class southwest side neighborhood. The area has deep meatpacking heritage and a strong, predominantly Hispanic community today.",
    vibe: "Working-class, heritage-rich, community-driven",
    transitAccess: "Orange Line (Ashland); CTA buses along Ashland, 47th, and Damen",
    rentRange: "$750–$1,100",
    notableFeatures: ["Union Stockyards Gate", "Back of the Yards heritage", "Sherman Park"],
  },
  "62": {
    name: "West Elsdon",
    description: "West Elsdon is a small, predominantly residential neighborhood on Chicago's southwest side. The area features well-kept brick bungalows, a diverse population, and affordable rents.",
    vibe: "Residential, quiet, affordable",
    transitAccess: "CTA buses along Pulaski and 55th; Orange Line accessible nearby",
    rentRange: "$800–$1,200",
    notableFeatures: ["Quiet residential streets", "Affordable bungalows", "Family-friendly"],
  },
  "63": {
    name: "Gage Park",
    description: "Gage Park is a diverse southwest side neighborhood with a large Hispanic population. The area is centered around the spacious Gage Park and features affordable housing and local businesses.",
    vibe: "Diverse, family-oriented, affordable",
    transitAccess: "CTA buses along Western, 55th, and California",
    rentRange: "$750–$1,100",
    notableFeatures: ["Gage Park (outdoor pool)", "Affordable housing", "Hispanic heritage"],
  },
  "64": {
    name: "Clearing",
    description: "Clearing is a small southwest side neighborhood adjacent to Midway Airport. The area has a suburban character with single-family homes, parks, and a strong community identity.",
    vibe: "Suburban, airport-adjacent, community-oriented",
    transitAccess: "Orange Line (Midway); CTA buses along 63rd and Central",
    rentRange: "$850–$1,300",
    notableFeatures: ["Midway Airport proximity", "Clearing Park", "Suburban atmosphere"],
  },
  "65": {
    name: "West Lawn",
    description: "West Lawn is a diverse residential neighborhood on the southwest side. The area features a mix of bungalows and apartment buildings with a growing Hispanic population and affordable rents.",
    vibe: "Residential, diverse, affordable",
    transitAccess: "CTA buses along 63rd, Pulaski, and Kedzie",
    rentRange: "$800–$1,200",
    notableFeatures: ["Marquette Park nearby", "Affordable housing", "Diverse community"],
  },
  "66": {
    name: "Chicago Lawn",
    description: "Chicago Lawn, also known as Marquette Park, is a diverse southwest side neighborhood centered around the beautiful 323-acre Marquette Park. The area offers affordable housing and strong community bonds.",
    vibe: "Diverse, green, community-bonded",
    transitAccess: "CTA buses along 63rd, Western, and California; Orange Line accessible",
    rentRange: "$750–$1,100",
    notableFeatures: ["Marquette Park (323 acres)", "Affordable bungalows", "Diverse community"],
  },
  "67": {
    name: "West Englewood",
    description: "West Englewood is a south side neighborhood with a resilient community working toward revitalization. The area features affordable housing and strong neighborhood organizations driving positive change.",
    vibe: "Resilient, community-organized, affordable",
    transitAccess: "Green Line (Ashland/63rd); CTA buses along 63rd and Ashland",
    rentRange: "$650–$950",
    notableFeatures: ["Affordable housing", "Community organizations", "Growing investment"],
  },
  "68": {
    name: "Englewood",
    description: "Englewood is a south side neighborhood undergoing significant community-led transformation. The area features new development including the Englewood Line trail and growing commercial investment.",
    vibe: "Transforming, community-led, developing",
    transitAccess: "Green Line (Halsted, Ashland/63rd); CTA buses along 63rd and Halsted",
    rentRange: "$650–$950",
    notableFeatures: ["Englewood Line trail", "New development", "Community investment"],
  },
  "69": {
    name: "Greater Grand Crossing",
    description: "Greater Grand Crossing is a south side neighborhood with a rich history and strong community networks. The area features affordable housing and is home to several important churches and cultural institutions.",
    vibe: "Historic, community-networked, faith-centered",
    transitAccess: "Metra Electric (75th St); CTA buses along 71st, 75th, and Cottage Grove",
    rentRange: "$700–$1,050",
    notableFeatures: ["Historic churches", "Affordable housing", "Community organizations"],
  },
  "70": {
    name: "Ashburn",
    description: "Ashburn is a stable, middle-class neighborhood on Chicago's southwest side. The area is known for its well-maintained brick bungalows, family-friendly atmosphere, and strong neighborhood watch programs.",
    vibe: "Stable, middle-class, family-friendly",
    transitAccess: "CTA buses along 79th, Kedzie, and Pulaski; Metra SWS nearby",
    rentRange: "$850–$1,300",
    notableFeatures: ["Well-maintained bungalows", "Neighborhood watch programs", "Family atmosphere"],
  },
  "71": {
    name: "Auburn Gresham",
    description: "Auburn Gresham is a south side neighborhood with a strong community identity and growing investment. The area features the 79th Street corridor and was selected for major city investment programs.",
    vibe: "Community-invested, growing, historically rich",
    transitAccess: "CTA buses along 79th, Halsted, and Ashland; Red Line nearby",
    rentRange: "$700–$1,050",
    notableFeatures: ["79th Street corridor", "INVEST South/West area", "Strong community identity"],
  },
  "72": {
    name: "Beverly",
    description: "Beverly is one of Chicago's most distinctive neighborhoods, known for its rolling hills, historic homes, and Irish-American heritage. The area hosts the annual South Side Irish Parade and features the Ridge Historic District.",
    vibe: "Historic, affluent, tight-knit",
    transitAccess: "Metra Rock Island (Beverly, 91st, 95th, 99th, 103rd, 107th); CTA buses along Western",
    rentRange: "$1,000–$1,700",
    notableFeatures: ["Ridge Historic District", "Beverly Arts Center", "South Side Irish Parade"],
  },
  "73": {
    name: "Washington Heights",
    description: "Washington Heights is a residential far south side neighborhood known for its attractive brick bungalows and tree-lined streets. The area offers an affordable, family-friendly environment with strong block club networks.",
    vibe: "Residential, family-friendly, organized",
    transitAccess: "Metra Rock Island (103rd St); CTA buses along 103rd and Halsted",
    rentRange: "$750–$1,100",
    notableFeatures: ["Attractive bungalows", "Strong block clubs", "Family-oriented"],
  },
  "74": {
    name: "Mount Greenwood",
    description: "Mount Greenwood is a tight-knit far south side neighborhood with a distinctly suburban character. The area is known for its well-maintained homes, active community organizations, and family-friendly atmosphere.",
    vibe: "Suburban, tight-knit, family-oriented",
    transitAccess: "Metra Rock Island (111th St); CTA buses along 111th and Western",
    rentRange: "$900–$1,400",
    notableFeatures: ["Suburban character", "Mount Greenwood Park", "Strong community bonds"],
  },
  "75": {
    name: "Morgan Park",
    description: "Morgan Park is a diverse far south side neighborhood with a mix of historic homes and natural beauty. The area features hilly terrain, mature trees, and a blend of urban and suburban character.",
    vibe: "Diverse, hilly, nature-oriented",
    transitAccess: "Metra Rock Island (Morgan Park, 115th St); CTA buses along 111th and Western",
    rentRange: "$800–$1,200",
    notableFeatures: ["Hilly terrain", "Historic homes", "Dan Ryan Woods Forest Preserve"],
  },
  "76": {
    name: "O'Hare",
    description: "O'Hare is dominated by Chicago O'Hare International Airport but also includes a small residential area. The neighborhood offers convenient airport access and nearby hotels and businesses.",
    vibe: "Airport-centric, transient, commercial",
    transitAccess: "Blue Line (O'Hare); CTA buses; airport shuttles",
    rentRange: "$900–$1,400",
    notableFeatures: ["O'Hare International Airport", "Hotel district", "Blue Line terminus"],
  },
  "77": {
    name: "Edgewater",
    description: "Edgewater is a diverse lakefront neighborhood known for the charming Andersonville commercial district. The area features beaches, vintage architecture, and a welcoming, LGBTQ-friendly atmosphere.",
    vibe: "Diverse, welcoming, lakefront living",
    transitAccess: "Red Line (Bryn Mawr, Berwyn); CTA buses along Broadway and Clark",
    rentRange: "$1,000–$1,700",
    notableFeatures: ["Andersonville district", "Kathy Osterman Beach", "Swedish American Museum"],
  },
};
